INSERT INTO ROOM(ID, NAME, LEVEL, STATUS) VALUES(-10, 'Room1', 20, 'ON');
INSERT INTO ROOM(ID, NAME, LEVEL, STATUS) VALUES(-9, 'Room2', 30, 'ON');

INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (-1, 8, 'ON', -10);
INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (-2, 0, 'OFF', -10);